const data = {
  states: [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Delhi',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jammu & Kashmir',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Maharashtra',
    'Madhya Pradesh',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Tripura',
    'Telangana',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
    'Andaman & Nicobar (UT)',
    'Chandigarh (UT)',
    'Dadra & Nagar Haveli (UT)',
    'Daman & Diu (UT)',
    'Lakshadweep (UT)',
    'Puducherry (UT)',
  ],
  bloodGroups: ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
  genders: ['Male', 'Female', 'Prefer Not to Say'],
  maritalStatus: ['Single', 'Married', 'Divorced', 'Widow/Widower'],
};

export default data;
