name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag kasamoke100/ursu-vedike:latest
    - name: Docker Login
      run: 
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Docker Push
      run: docker push kasamoke100/ursu-vedike:latest
